### ISSUE TITLE
vA3C JSON Loader

### ISSUE THREAD

**Issue by ibuilder** [va3c/viewer#3]
is there a loader for vA3C JSON files with three.js?  It seems as though the normal three.js [JSON loader](http://threejs.org/docs/#Reference/Loaders/JSONLoader) does not have geometries and a breakdown like the JSON files exported from the vA3C plugins.  Is there a JSON Loader file that I can add to my viewer for specifically vA3C files?

**Comment by theo-armour** [comment]
Matthew

I have generally been following the Three.js Editor loader code:

https://github.com/mrdoob/three.js/blob/master/editor/js/Loader.js

There will be a new revision - r5 - to the vA3C Viewer in the next day or
so that will have much broader loading capabilities as well as much
simpler, tighter code.

So you should soon have two locations to see how the loading can be handled.

If you have some sample files, I would be delight to see if the vA3C view
can load them and to provide feedback on what I find.

---

BTW would you like to be added to the vA3C Google Group so that you hear
about updates?

Theo

**Comment by ibuilder** [comment]
@theo-armour Yes, That would be great!
